version: '2'
services:
    projetjhipster1-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/ProjetJHipster1/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ProjetJHipster1
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
